trecapps.routes.backend.User-api=http://localhost:8082
trecapps.routes.backend.Image-man-api=http://localhost:8081
trecapps.routes.backend.falsehoods=http://localhost:8083
trecapps.routes.backend.sm-api=http://localhost:8092
trecapps.routes.backend.message-notify=http://localhost:8093
trecapps.routes.backend.mn-api=http://localhost:8093
trecapps.routes.backend.trec-store=http://localhost:8084

trecapps.route.single=/mn-api/ws/**;ws://localhost:8093;1

