trecapps.routes.backend.User-api=${USER_API_URL}
trecapps.routes.backend.Image-man-api=${IMAGE_API_URL}
trecapps.routes.backend.falsehoods=${FALSEHOODS_API_URL}

# Details, in the form of "{route 1}, {route 2}...{route n}|URL"
trecapps.routes.frontends.users=${USER_NG_DETAILS}